NETWORK_PASSPHRASE = "Pi Testnet"
VERSION = "3.1.4"

[DOCUMENTATION]
ORG_NAME = "Tran Van Dinh"
ORG_URL = "https://tranvandinh128.github.io"
ORG_LOGO = "https://tranvandinh128.github.io/logo.png"
ORG_DESCRIPTION = "NLD Token ecosystem developed for Pi Network Testnet."

# Official Accounts
ACCOUNTS = [
"GBMZ5W4R7IYTVP6FIN4NT5CUIBETYFKNVXEIQ4XNEDNILUKBLLD6RZNU", # Issuer
"GARC4SECUCG7OMFNJSLCL4LLZMGDY46BEIQQPHO36SNSYLQT3WSVVPUA"  # Distribution
]

[[CURRENCIES]]
code = "NLD"
issuer = "GBMZ5W4R7IYTVP6FIN4NT5CUIBETYFKNVXEIQ4XNEDNILUKBLLD6RZNU"
name = "NLD Token"
desc = "NLD token developed by Tran Van Dinh for commerce and ecosystem applications on Pi Network."
image = "https://tranvandinh128.github.io/logo.png"
status = "test"
display_decimals = 7
conditions = "Available for Pi Testnet educational and ecosystem purposes."