NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

ACCOUNTS=[
"GBMZ5W4R7IYTVP6FIN4NT5CUIBETYFKNVXEIQ4XNEDNILUKBLLD6RZNU",
"GARC4SECUCG7OMFNJSLCL4LLZMGDY46BEIQQPHO36SNSYLQT3WSVVPUA"
]

[[CURRENCIES]]
code="NLD"
issuer="GBMZ5W4R7IYTVP6FIN4NT5CUIBETYFKNVXEIQ4XNEDNILUKBLLD6RZNU"
display_decimals=7
name="Nhan Lac Do Token"
desc="NLD token for Nhan Lac Do ecosystem on Pi Network Testnet"
conditions="Token used for trading and services in ecosystem."
image="https://tranvandinh128.github.io/logo.png"
