NETWORK_PASSPHRASE="Pi Testnet"

ACCOUNTS=[
"GBMZ5W4R7IYTVP6FIN4NT5CUIBETYFKNVXEIQ4XNEDNILUKBLLD6RZNU"
]

[[CURRENCIES]]
code="NLD"
issuer="GBMZ5W4R7IYTVP6FIN4NT5CUIBETYFKNVXEIQ4XNEDNILUKBLLD6RZNU"
display_decimals=2
name="Nhan Lac Do Token"
desc="Token NLD in Pi ecosystem"
